### ISSUE TITLE
Not working for user names different than 'mdeheij'

### ISSUE THREAD

**Issue by pepijnvanleeuwen** [mdeheij/linux-essentials#1]
When you run the shell script, the script will break when your user name does not equal `mdeheij`. It also breaks when the folder `/home/mdeheij/Downloads` does not exist.

Could you use `~/*` instead of the fixed path `/home/mdeheij/*`?

**Comment by mdeheij** [comment]
Thanks! Will look into this very soon.

**Comment by mdeheij** [comment]
Fixed! It uses your own home instead of mine now! Thank you again for reporting this.

**Comment by pepijnvanleeuwen** [comment]
Thanks!
